Notes: Jenkins pipeline
project: cds
services:
  backend:
    version: 2.2.0-vul-fix.123
    image: 2.2.0-vul-fix.123
    buildNumber: '123'
  frontend:
    version: 4.3.0-vul-fix.305
    image: 4.3.0-vul-fix.305
    buildNumber: '305'
  interoperation:
    version: 1.0.0.36
    image: 1.0.0.36
    buildNumber: '36'
