Notes: Jenkins pipeline
project: cds
services:
  backend:
    version: 2.1.0.48
    image: 2.1.0.48
    buildNumber: '48'
  frontend:
    version: 4.1.0.213
    image: 4.1.0.213
    buildNumber: '213'
