Notes: Jenkins pipeline
project: cds
services:
  backend:
    version: 2.1.0.90
    image: 2.1.0.90
    buildNumber: '90'
  frontend:
    version: cds_velsera_hotfix.268
    image: cds_velsera_hotfix.268
    buildNumber: '268'
  interoperation:
    version: 1.0.0.33
    image: 1.0.0.33
    buildNumber: '33'
