Notes: Jenkins pipeline
project: cds
services:
  backend:
    version: 2.1.0.90
    image: 2.1.0.90
    buildNumber: '90'
  frontend:
    version: 4.2.0.225
    image: 4.2.0.225
    buildNumber: '225'
  interoperation:
    version: 1.0.0.36
    image: 1.0.0.36
    buildNumber: '36'

