Notes: Jenkins pipeline
project: cds
services:
  backend:
    version: 2.1.1.98
    image: 2.1.1.98
    buildNumber: '98'
  frontend:
    version: 4.3.0.282
    image: 4.3.0.282
    buildNumber: '282'
  interoperation:
    version: 1.0.0.36
    image: 1.0.0.36
    buildNumber: '36'
