Notes: Jenkins pipeline
project: cds
services:
  backend:
    version: 2.0.0.20
    image: 2.0.0.20
    buildNumber: '20'
  frontend:
    version: 4.0.0.186
    image: 4.0.0.186
    buildNumber: '186'
