Notes: Jenkins pipeline
project: cds
services:
  backend:
    version: 2.2.0.131
    image: 2.2.0.131
    buildNumber: '131'
  frontend:
    version: 4.4.0.319
    image: 4.4.0.319
    buildNumber: '319'
  interoperation:
    version: 1.1.0.45
    image: 1.1.0.45
    buildNumber: '45'
