Notes: Jenkins pipeline
project: cds
services:
  backend:
    version: 2.0.0.21
    image: 2.0.0.21
    buildNumber: '21'
  frontend:
    version: 4.0.0.189
    image: 4.0.0.189
    buildNumber: '189'
