Notes: Jenkins pipeline
project: cds
services:
  backend:
    version: 2.1.0.39
    image: 2.1.0.39
    buildNumber: '39'
  frontend:
    version: 4.0.0.206
    image: 4.0.0.206
    buildNumber: '206'