Notes: Jenkins pipeline
project: cds
services:
  backend:
    version: 2.1.0.90
    image: 2.1.0.90
    buildNumber: '90'
  frontend:
    version: 4.2.0.269
    image: 4.2.0.269
    buildNumber: '269'
  interoperation:
    version: 1.0.0.33
    image: 1.0.0.33
    buildNumber: '33'
