---
# tasks file for neo4j-dump

- name: ensure that remote workspace exists
  file:
    path: "{{ remote_workspace }}-{{ tier }}"
    state: directory

- name: verify file is present
  stat:
     path: "{{ remote_workspace }}-{{ tier }}/{{ dump_file_name }}.dump"
  register: file_status

# - name: upload dump file to s3
#   aws_s3:
#     bucket: "{{ s3_bucket_name }}"
#     object: "/{{ s3_folder_name }}/{{ dump_file_name }}-{{ timestamp }}.dump"
#     src: "{{ remote_workspace }}-{{ tier }}/{{ dump_file_name }}.dump"
#     mode: put

- name: all the options
  community.aws.s3_sync:
    bucket: "{{ s3_bucket_name }}"
    file_root: "{{ remote_workspace }}-{{ tier }}/{{ dump_file_name }}.dump"
    key_prefix: "{{ s3_folder_name }}"
    file_change_strategy: force
    
# - name: upload dump file to s3
#   aws_s3:
#     bucket: "{{ s3_bucket_name }}"
#     object: "/{{ s3_folder_name }}/{{ dump_file_name }}-{{ timestamp }}.dump"
#     src: "{{ remote_workspace }}-{{ tier }}/{{ dump_file_name }}.dump"
#     mode: put