---
- name: push dump file to s3
  hosts: all
  connection: local
  gather_facts: yes
    
  tasks:
    - name: push dump file
      include_role:
        name: data-processing
        tasks_from: icdc-data-dump-push
        vars_from: icdc_data_dump