
---
- name: dump data from neo4j db
  hosts: all
  gather_facts: yes
  become: yes
  remote_user: commonsdocker
  tasks:
    - name: perform data dump
      include_role:
        name: data-processing
        tasks_from: icdc-data-dump
        vars_from: icdc_data_dump
