
---
- name: dump data from neo4j db
  hosts: all
  gather_facts: yes
  become: yes
  remote_user: commonsdocker
  tasks:
  #install collections
    - name: install aws collection
      command: ansible-galaxy collection install {{item}}
      loop:
        - community.docker
        - amazon.aws
        # - community.aws:<=3.2.0
        - git+https://github.com/CBIIT/datacommons-devops.git#/ansible/collections/bento/common/,neo4j-dump
    
    - name: 
      include_role:
        name: bento.common.neo4j_dump
        tasks_from: data-dump
        vars_from: main
        
