- name: Get the current caller identity information
  aws_caller_info:
  register: caller_info

- name: Get ECR account
  set_fact:
    ecr_central_account_id: "{{ lookup('amazon.aws.aws_secret', 'ecr.central_account_id', nested=true, region='us-east-1' ) }}"
- name: set ECR registry name
  set_fact:
    ecr_repo: "{{ecr_central_account_id}}.dkr.ecr.{{ region }}.amazonaws.com"
    account: "{{ caller_info.account }}"

- name: login into ecr
  shell: "docker login -u AWS -p $(aws ecr get-login-password --region {{ region }}) {{ ecr_repo }}"
  ignore_errors: True
  register: ecr_login

- debug:
  msg: "{{ecr_login}}"